name: polypwn-instancer
services:
  instancer:
    build: .
    ports:
      - "8080:8080"
    entrypoint:
        - "./instancer"
        - "serve"
        - "8080"
        - "--config"
        - "data/config.yaml"
    volumes:
      - ./data/:/app/data/:Z

    restart: unless-stopped
